#!/bin/sh -x 

# SUBMIT_CHECK_RESULT
# Written by Ethan Galstad (egalstad@nagios.org)
# Last Modified: 02-18-2002
#
# This script will write a command to the Nagios command
# file to cause Nagios to process a passive service check
# result.  Note: This script is intended to be run on the
# same host that is running Nagios.  If you want to 
# submit passive check results from a remote machine, look
# at using the nsca addon.
#
# Arguments:
#  $1 = host_name (Short name of host that the service is
#       associated with)
#  $2 = svc_description (Description of the service)
#  $3 = return_code (An integer that determines the state
#       of the service check, 0=OK, 1=WARNING, 2=CRITICAL,
#       3=UNKNOWN).
#  $4 = plugin_output (A text string that should be used
#       as the plugin output for the service check)
# 
 
echocmd="/bin/echo"
 
CommandFile="/usr/local/nagios/var/rw/nagios.cmd"
 
# get the current date/time in seconds since UNIX epoch
datetime=`date +%s`

HOST="123"

echo "input: $1" >> /tmp/submit_trap.log

echo $1 | egrep "^[0-9]" > /dev/null 2>&1

if [[ $? -eq 0 ]]
then
	host $1 10.10.26.3 | grep "not found" > /dev/null 2>&1
	if [ $? -eq 1 ]
	then
		HOST="`host $1 10.10.26.3 | grep pointer | awk '{print $5}' | sed 's/local./local/g' | awk '{print tolower($0)}' | sed -e '/^$/d'`"
	else
		host $1 10.10.21.1 | grep "not found" > /dev/null 2>&1
		if [ $? -eq 1 ]
		then
			HOST="`host $1 10.10.21.1 | awk '{print $5}' | awk '{print tolower($0)}' | sed -e '/^$/d'`"
							#sed 's/.wh.reachlocal.com.//g' | sed 's/.wh.reachlocal.net.//g' | awk '{print tolower($0)}' | sed -e '/^$/d'`"
			echo $HOST | grep -i "dyn.wh"
			if [ $? -eq 0 ]
			then
				HOST=`echo $HOST | sed 's/.wh.reachlocal.com.//g'`
			fi
		else
			#getent hosts 10.10.24.30 | awk '{print $2}'
			host $1 | grep "not found" > /dev/null 2>&1
			if [ $? -eq 1 ]
			then
				HOST="`host $1 | awk '{print $5}' | sed 's/.reachlocal.com.//g' | sed 's/.reachlocal.net.//g' | awk '{print tolower($0)}' | sed -e '/^$/d'`"
			else
				HOST="`getent hosts $1 | awk '{print $2}' | sed -e '/^$/d'`"
							#sed 's/.reachlocal.com.//g' | sed 's/.reachlocal.net.//g' | awk '{print tolower($0)}' | sed -e '/^$/d'`"
			fi
		fi
	fi
fi

if [[ $HOST == 1* ]]
then
	HOST=`echo $1 | sed 's/.wh.reachlocal.com.//g'`
fi

echo $HOST | grep "dyn" > /dev/null 2>&1
if [ $? -eq 0 ]
then
	HOST=`echo $HOST | sed 's/.wh.reachlocal.com//g' | sed 's/.wh//g'`
fi

echo $HOST | egrep "qstr.*h$" > /dev/null 2>&1
if [ $? -eq 0 ]
then
	HOST="$HOST.reachlocal.com"
fi

echo $HOST | egrep "^123" > /dev/null 2>&1
if [[ $? -ne 0 ]] 
then
	cmdline="[$datetime] PROCESS_SERVICE_CHECK_RESULT;$HOST;$2;$3;$4"
else
	cmdline="[$datetime] PROCESS_SERVICE_CHECK_RESULT;$1;$2;$3;$4"
fi

echo "$(date)" >> /tmp/submit_trap.log
echo "$cmdline" >> /tmp/submit_trap.log
# append the command to the end of the command file
`$echocmd $cmdline >> $CommandFile`
